openapi: 3.1.0
info:
  title: ECHOHUB API
  description: >-
    API Endpoints for the ECHOHUB Project.


    # Authentication

    Authentication is a process by which a system verifies the identity of a
    user accessing this API.       


    <!-- ReDoc-Inject: <security-definitions> -->
  version: v1
  termsOfService: https://example.com
  contact:
    name: ECHO Health Inc.
    url: https://echohealthinc.com
    email: Echo_Hub@echohealthinc.com
servers:
  - url: /v1
security:
  - x-ApiKey: []
    x-ClientKey: []
paths:
  /api/eCheck/v1/MPXECheckPayeeContact:
    $ref: paths/api@eCheck@v1@MPXECheckPayeeContact.yaml
  /api/DirectPay/Deluxe/v1/DeluxeEcheck:
    $ref: paths/api@DirectPay@Deluxe@v1@DeluxeEcheck.yaml
  /api/DirectPay/Deluxe/v1/DeluxeEcheckCancel:
    $ref: paths/api@DirectPay@Deluxe@v1@DeluxeEcheckCancel.yaml
  /api/MedPay/V1/UpdateBlockedVCard:
    $ref: paths/api@MedPay@V1@UpdateBlockedVCard.yaml
  /api/payhub/v1/MedPayAPEXPayment:
    $ref: paths/api@payhub@v1@MedPayAPEXPayment.yaml
  /api/SelectPay/v1/Portal:
    $ref: paths/api@SelectPay@v1@Portal.yaml
  /api/VCP/V1/RealTime:
    $ref: paths/api@VCP@V1@RealTime.yaml
  /api/VCP/V1/Cancel:
    $ref: paths/api@VCP@V1@Cancel.yaml
  /api/DirectPay/DirectToDebit/v1/DirectToDebitPayment:
    $ref: paths/api@DirectPay@DirectToDebit@v1@DirectToDebitPayment.yaml
  /api/DirectPay/DirectToDebit/v1/DirectToDebitCancel:
    $ref: paths/api@DirectPay@DirectToDebit@v1@DirectToDebitCancel.yaml
  /api/DirectPay/DirectToDebit/v1/DirectToDebitStatus:
    $ref: paths/api@DirectPay@DirectToDebit@v1@DirectToDebitStatus.yaml
  /api/DirectPay/DirectToDebit/v1/VenmoPayment:
    $ref: paths/api@DirectPay@DirectToDebit@v1@VenmoPayment.yaml
  /api/DirectPay/DirectToDebit/v1/VenmoCancel:
    $ref: paths/api@DirectPay@DirectToDebit@v1@VenmoCancel.yaml
  /api/DirectPay/DirectToDebit/v1/VenmoStatus:
    $ref: paths/api@DirectPay@DirectToDebit@v1@VenmoStatus.yaml
  /api/DirectPay/v1/PaymentCancel [For Deluxe]:
    $ref: paths/UniversalCancel/api@DirectPay@v1@UniversalDeluxeCancel.yaml
  /api/DirectPay/v1/PaymentCancel [For Direct To Debit] :
    $ref: paths/UniversalCancel/api@DirectPay@v1@UniversalDirectToDebitCancel.yaml
  /api/DirectPay/v1/PaymentCancel [For Venmo] :
    $ref: paths/UniversalCancel/api@DirectPay@v1@UniversalVenmoCancel.yaml
  /api/DirectPay/v1/PaymentCancel [For Zelle] :
    $ref: paths/UniversalCancel/api@DirectPay@v1@UniversalZelleCancel.yaml
  /api/DirectPay/v1/PaymentCancel [For VCP] :
    $ref: paths/UniversalCancel/api@DirectPay@v1@UniversalVCPCancel.yaml
  /api/DirectPay/v1/PaymentStatus [For Direct To Debit] :
    $ref: paths/UniversalStatus/api@DirectPay@v1@UniversalDirectToDebitStatus.yaml
  /api/DirectPay/v1/PaymentStatus [For Venmo] :
    $ref: paths/UniversalStatus/api@DirectPay@v1@UniversalVenmoStatus.yaml
  /api/DirectPay/v1/PaymentStatus [For Zelle] :
    $ref: paths/UniversalStatus/api@DirectPay@v1@UniversalZelleStatus.yaml
  /api/DirectPay/v1/PaymentStatus [For VCP] :
    $ref: paths/UniversalStatus/api@DirectPay@v1@UniversalVCPStatus.yaml
  /api/DirectPay/v1/PaymentVoid:
    $ref: paths/UniversalVoid/api@DirectPay@v1@UniversalDeluxeVoid.yaml 
components:
  securitySchemes:
    x-ApiKey:
      type: apiKey
      name: x-ApiKey
      description: The API key.
      in: header
    x-ClientKey:
      type: apiKey
      description: The client key.
      name: x-ClientKey
      in: header
tags:
  - name: eCheck
    description: >
      An eCheck, or electronic check, is a digital version of a paper check that
      is used to make a payment online.    

      With an eCheck, money is electronically withdrawn from the Payer’s
      checking account.  

      Money is transferred over the ACH (Automated Clearing House) network and
      deposited into the Payee’s checking account.

  - name: Direct To Debit
    description: |
     Direct To Debit is the simplest and most convenient way to make payments. It is a type of pre-authorized payment which allows a bank to pay certain amount directly to the Provider with a debit card. With Direct To Debit payments, the money is directly transferred to the card holder.  
     Direct To Debit has three endpoints:
      * Direct To Debit payment create
      * Direct To Debit payment status
      * Direct To Debit payment cancel
  
  - name: Venmo
    description: |
     Venmo is a payment app available on iPhones and Android phones that allows for the quick and easy exchange of money. A user with a Venmo account can transfer funds to the Payee bank account without needing cash or checks. Venmo account can be linked to credit card, debit card, or checking accounts. Venmo is more like a digital wallet where funds are held as a Venmo balance in the checking account.  
     Venmo has three endpoints:
      *	Venmo payment create
      *	Venmo payment status
      *	Venmo payment cancel

